[package]
name = "bevy_editor_undo"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
